/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.home.tutorial.p1;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CalculatorTest {
    //methodName_stateUnderTest_expectedBehavior()
    @Test
    void divide_validInput_returnSuccessfully() {
        //Arrange
        final var calculator = new Calculator();

        int i = 23, j = 5;
        final int expected = 4;
        //Act
        final var actual = calculator.divide(i, j);
        //Assertion
        assertEquals(expected, actual);
    }
}
