/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.home.tutorial.junit.p1;

import ir.home.tutorial.junit.p1.tags.FastTest;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
@IndicativeSentencesGeneration(separator = "@", generator = DisplayNameGenerator.IndicativeSentences.class)
class CalculatorTest {
    //methodName_stateUnderTest_expectedBehavior()

    @FastTest
//    @DisplayName("🤣fadsjlfkdsajf afkjadslf;jadsf;klasd")
    void divide_validInput_returnSuccessfully() {
        //Arrange
        final var calculator = new Calculator();

        int i = 23, j = 5;
        final int expected = 4;
        //Act
        final var actual = calculator.divide(i, j);
        //Assertion
        assertEquals(expected, actual);
    }

    @Nested
    class A_year_is_a_leap_year {

        @BeforeAll
        static void t() {
//            fail("Java allows static members in inner classes!");
        }

        @Test
        void tt() {
            Assertions.assertTrue(true);
        }
    }
}
